# Generated by Django 2.0.2 on 2018-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='brief',
            field=models.CharField(default='暂无', max_length=512, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=20, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='usage',
            field=models.CharField(max_length=64, null=True, verbose_name='用量'),
        ),
    ]
