# Generated by Django 2.0.2 on 2018-02-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20180227_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='usage',
            field=models.CharField(max_length=128, null=True, verbose_name='用量'),
        ),
    ]
