# Generated by Django 2.0.2 on 2018-02-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20180209_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='邮箱'),
        ),
    ]
