# Generated by Django 2.0.2 on 2018-02-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20180209_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytype',
            options={'ordering': ['add_time'], 'verbose_name_plural': '菜谱菜单分类'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': '食材'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['join_time'], 'verbose_name_plural': '会员'},
        ),
        migrations.AlterModelOptions(
            name='memberrecipelist',
            options={'ordering': ['add_time'], 'verbose_name_plural': '用户创建的菜谱菜单'},
        ),
        migrations.AlterModelOptions(
            name='nutrition',
            options={'ordering': ['add_time'], 'verbose_name_plural': '营养成分'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['add_time'], 'verbose_name_plural': '菜谱'},
        ),
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'ordering': ['add_time'], 'verbose_name_plural': '菜谱分类'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name_plural': '菜谱食材关联关系'},
        ),
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['add_time'], 'verbose_name_plural': '步骤'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'ordering': ['add_time'], 'verbose_name_plural': '标签'},
        ),



        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=24, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_fake',
            field=models.IntegerField(default=0, verbose_name='如果是爬虫抓的话，就给这个字段1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=12, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='memberrecipelist',
            name='last_modify_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='category_type',
            field=models.ManyToManyField(db_constraint=False, to='front.CategoryType'),
        ),
    ]
