# Generated by Django 2.0.2 on 2018-03-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20180305_2029'),
        ('front', '0004_auto_20180227_2325'),
    ]

    operations = [
    ]
