# Generated by Django 2.0.2 on 2018-03-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_merge_20180306_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.EmailField(db_index=True, max_length=16, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='姓名'),
        ),
        migrations.RemoveField(
            model_name='memberrecipelist',
            name='fav_by',
        ),
        migrations.AddField(
            model_name='memberrecipelist',
            name='fav_by',
            field=models.ManyToManyField(db_constraint=False, related_name='collected_lists', to='front.Member'),
        ),
        migrations.AlterField(
            model_name='memberrecipelist',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='名称'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fav_by',
        ),
        migrations.AddField(
            model_name='recipe',
            name='fav_by',
            field=models.ManyToManyField(db_constraint=False, related_name='collected_recipe', to='front.Member'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='名称'),
        ),
    ]
