# Generated by Django 2.0.2 on 2018-03-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20180308_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='tips',
            field=models.CharField(default='暂无', max_length=4096, verbose_name='食材烹饪小窍门'),
        ),
    ]
