# Generated by Django 2.0.2 on 2018-03-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_auto_20180309_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='stars',
            field=models.IntegerField(default=0, max_length=16, verbose_name='点赞数'),
        ),
    ]
