# Generated by Django 2.0.2 on 2018-03-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_recipe_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='brief',
            field=models.CharField(default='暂无', max_length=2048, verbose_name='简介'),
        ),
    ]
