# Generated by Django 2.0.2 on 2018-03-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20180315_0110'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='recipe',
        #     name='brief',
        # ),
        # migrations.RemoveField(
        #     model_name='recipe',
        #     name='extra',
        # ),
        # migrations.RemoveField(
        #     model_name='recipe',
        #     name='notice',
        # ),
    ]
